### ISSUE TITLE
struct.error: unpack requires a buffer of 12 bytes

### ISSUE THREAD

**Issue by Pattern6** [weiyithu/NerfingMVS#13]
Hello,author！I want to ask you some questions about running code and reporting errors.I run it step by step according to the steps in your readme, but I'm running sh run.sh scene0000_01,after running for about 20minutes,an error was reoprted as follow:
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    depth_priors.train(args)
  File "/home/ubuntu/ygx/NerfingMVS-main/src/depth_priors.py", line 70, in train
    args.depth_H, args.depth_W)
  File "/home/ubuntu/ygx/NerfingMVS-main/utils/io_utils.py", line 27, in load_colmap
    ply_masks = read_ply_mask(ply_path)
  File "/home/ubuntu/ygx/NerfingMVS-main/utils/colmap_utils.py", line 62, in read_ply_mask
    load_point_vis(ply_vis_path, masks)
  File "/home/ubuntu/ygx/NerfingMVS-main/utils/colmap_utils.py", line 41, in load_point_vis
    idx, u, v = struct.unpack('<III', f.read(4 * 3))
struct.error: unpack requires a buffer of 12 bytes
I have also consulted the relevant information about error reporting, but it still can't be solved. I hope author can give some solutions.Thank you!

**Comment by KopanevPavel** [comment]
Have you checked #9 ?

**Comment by weiyithu** [comment]
I thint it may beacause you use original COLMAP instead of our version's COLMAP. Please refer to #2
